spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: Gauri@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
    database: postgresql
  mail:
    username: gauri@weetechsolution.com
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
application:
  security:
    jwt:
      secrete-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 600000 # for 10 minutes
      refresh-key:
        expiration: 86400000  # for 24 hours
security:
  jwt:
    username: pri-user
    password: pri-pass

